import type { Models } from 'node-appwrite';

// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types --language ts ./types`.

export type Projects = Models.Row & {
    title: string;
    description: string;
    problematic: string;
    objectives: string;
    features: string;
    constraints: string;
    user: Users;
}

export type Users = Models.Row & {
    email: string;
    username: string;
    projects: Projects[];
}
